name: Bug
description: Reporta un problema reproducible con la app.
title: "BUG: [breve resumen]"
labels: [ "bug" ]
assignees: []
body:
- type: dropdown
  id: severidad
  attributes:
    label: Severidad
    options:
    - Crítico
    - Alto
    - Medio
    - Bajo
  validations:
    required: true
- type: textarea
  id: pasos
  attributes:
    label: Pasos para reproducir
    description: Lista los pasos exactos para reproducir el problema.
    placeholder: "1) ...\n2) ...\n3) ..."
  validations:
    required: true
- type: textarea
  id: resultado_esperado
  attributes:
    label: Resultado esperado
    placeholder: "Qué debería ocurrir"
  validations:
    required: true
- type: textarea
  id: resultado_actual
  attributes:
    label: Resultado actual
    placeholder: "Qué ocurre actualmente"
  validations:
    required: true
- type: textarea
  id: entorno
  attributes:
    label: Entorno
    description: SO, versión app, logs relevantes, GPU/CPU si aplica.
    placeholder: "Windows 11, vX.Y.Z, ..."
- type: textarea
  id: adjuntos
  attributes:
    label: Evidencia
    description: Pega logs o URLs de imágenes/videos.
