name: User Story
description: Crea una historia con criterios de aceptación claros.
title: "US: [breve resumen]"
labels: [ "story" ]
assignees: []
body:
- type: input
  id: epic
  attributes:
    label: Épica (número o URL)
    description: Indica la épica relacionada o pega el URL del issue épico.
    placeholder: "p.ej., ÉPICA 3 o https://github.com/<owner>/<repo>/issues/6"
  validations:
    required: true
- type: textarea
  id: detalle
  attributes:
    label: Detalle
    description: Contexto, alcance y motivación del usuario.
    placeholder: "Como <rol>, quiero <objetivo> para <beneficio>"
  validations:
    required: true
- type: textarea
  id: criterios
  attributes:
    label: Criterios de aceptación
    description: Lista de criterios verificables (Gherkin opcional).
    placeholder: "- Dado/Cuando/Entonces...\n- ..."
  validations:
    required: true
- type: dropdown
  id: prioridad
  attributes:
    label: Prioridad
    options:
    - Alta
    - Media
    - Baja
  validations:
    required: false
- type: input
  id: story_points
  attributes:
    label: Story points
    placeholder: "3, 5, 8..."
- type: checkboxes
  id: dod
  attributes:
    label: Checklist DoD
    description: Marca lo que aplica antes de cerrar la historia.
    options:
    - label: Código funcional y testeado
    - label: UI estable
    - label: Documentado
    - label: Integrado en main branch
    - label: Aprobado por PO
