name: Task
description: Crea una tarea técnica o de soporte.
title: "TASK: [breve resumen]"
labels: [ "task" ]
assignees: []
body:
- type: textarea
  id: objetivo
  attributes:
    label: Objetivo
    description: Qué se quiere lograr y por qué.
  validations:
    required: true
- type: textarea
  id: entregables
  attributes:
    label: Entregables
    description: Artefactos o cambios esperados.
    placeholder: "- Código en ...\n- Docs en ..."
- type: checkboxes
  id: dod
  attributes:
    label: Definition of Done
    options:
    - label: Implementado y testeado
    - label: Documentado
    - label: Integrado en main branch
